Merged revision(s) 1518-1618 from branches/exOdbc_cMake: just start with something for the exodbc lib ........ compiles using cmake, just add the resource files and maybe precompiled headers ........ Versioning works too ........ Versioning works too ........ Add a directory for all the test-stuff. fix version ........ Add test-sources ........ move resources to a subdir res ........ output to bin directory (inside build-folder), add resources. ........ rename test-rc file ........ try to add generated config file to project.. ........ remove all precompiled header stuff, I notice no difference in speed during compilation ........ try to add top-level CMakeLists.txt, seems to work ........ where do we want to define the versions? ........ cleanup ........ start playing with the test-project. ........ some minimal install notes
........
First steps for exOdbcTest
........
broken?
........
configure works
........
we need to link exodbctest against boot libraries now.
........
completely reogranize the structure and simplify a lot
........
and more reorg
........
library compiles with new structure.
........
fix path for config files, update INSTALL.txt with notes about how to export BOOST_ROOT
........
simplify
........
some tweaking about being more constant with naming
........
more notes and hints
........
Fix for the env var notes
........
add some messages and set a default
........
No precompiled headers
........
remove all includes of stdafx.h
........
some comment
........
Fix includes for libexodbc. gets included now in test
........
Fix includes from stdafx.h
........
Fix more errors from stdafx.h
compiles like this, still fails to link.
........
link against libexodbc. just import if libexodbc_EXPORTS is not defined.
........
building googletest works
........
no need for targetver.h
........
almost there with boost linking.. just need to link against dynamic not static..
........
more progress on boost linking
........
tests compile for the first time
........
Disable building of gmock
........
fix comment
........
Use options, not env-vars.
........
update notes
........
correct linking with boost (-gd or not)
........
Copying TestSettings.xml works
........
use 1.8.0 googletest
........
some cleanup
........
linking against boost static or dynamic on win32 works
........
64bit also works
........
fix message
........
Fix of Revision: 1553 - we need to make sure nothing is defined if creating static libs.
Author: eg
Date: Dienstag, 27. Dezember 2016 17:17:37
Message:
link against libexodbc. just import if libexodbc_EXPORTS is not defined.
----
Modified : /branches/exOdbc_cMake/CMakeLists.txt
Modified : /branches/exOdbc_cMake/include/exodbc/exOdbc.h
Modified : /branches/exOdbc_cMake/test/CMakeLists.txt


........
some more doc. default samples to on. do not set build type.
........
Fix version information.
........
fix spelling
........
fix spelling
........
update doc for Release and Debug
........
Add DatabaseInfo/CMakeLists.txt 
........
and shortintro sample.
........
all samples compile
........
move lic
........
Some more doc.
........
Add TestSettings.xml to the generated project
........
some tests for running the tests
........
remove #include "boost/variant/polymorphic_get.hpp"
........
some #ifdefs for windows-only things.
........
update notes about sql
........
Do not do Subversion_WC_LOG, it requires credentials 

........
Fix ddlimport and export for gcc

........
Remove warning about ; at endif

........
Some more fixes and tries for compiling under linux

........
Bitmask errors left

........
need __FUNCTIONW__on windows
........
compiles under windows again.
........
Add some output about sizeof_void

........
Fix EnumFlags to compile with gcc. note: 0 is not the same as nullptr, in std::enable_if

........
Fix extra namesapce in function signature.

........
remove a lot of warning like /home/eli/dev/exOdbc_cMake/src/Database.cpp:363:90: warning: passing NULL to non-pointer argument 4 of 'SQLRETURN SQLGetConnectAttr(SQLHDBC, SQLINTEGER, SQLPOINTER, SQLINTEGER, SQLINTEGER*)' [-Wconversion-null]


........
remove warnings like /home/eli/dev/exOdbc_cMake/src/Database.cpp:769:101: warning: converting to non-pointer type 'long int' from NULL [-Wconversion-null]


........
Fix things, do not break them!

........
some preparation for wstring with linux odbc api

........
at least in windows a test in ReadCatalog still works with this primitive chartypestuff
........
ReadCatalogInfo has no errors on linux now, but does it still work on wi?

........
compiles with windows, tests run
........
Provide overload for the utf..to..whatever that directly work with SQLCHAR*

........
Fix api calls in Database.cpp

........
Add MAX_PATH from limits.h using PATH_MAX

........
environment compiles

........
ExecutableStatement compiles

........
GetAllErrors

........
fix helpers.cpp and i love const

........
i hate if without { } 

........
okay, now its about streams.. in FileLogHandler

........
mess in FileLogHandler, see #238

compiles, but fails to link.

........
Fix multiple definitions of templated BindColumn and BindParameter functions.
See http://stackoverflow.com/questions/4445654/multiple-definition-of-template-specialization-when-using-different-objects
maybe we should just move that impl into the cpp file..

........
need more reinterpret_casts

........
compiles, but does not link

........
Fix linking against odbc in linux, not odbc32

........
samples compile

........
some playing around with encodings. 

........